In [7]:
def research(x,y):
    for i in x:
        for j in y:
            if i == j:
                print(i)
                break

In [10]:
research('мама', 'папа')

а
а


In [8]:
for i in range(0,10,1):
    print(i,end=' ')

0 1 2 3 4 5 6 7 8 9 

In [13]:
range(1,5) #создание набора целых чисел, по умолчанию шаг - один, шаг - тоже целое число

range(1, 5)

In [14]:
range(1,5)[:2]

range(1, 3)

In [15]:
list(range(1,5))

[1, 2, 3, 4]

In [16]:
len(range(1,5))

4

In [17]:
range(0,3,2) == range(0,4,2)

True

In [20]:
import numpy as np
a = np.array([1, 2, 3]) #создание массивов целых чисел
a

array([1, 2, 3])

In [21]:
b = np.arange(10, 30, 5)
b

array([10, 15, 20, 25])

In [22]:
c = np.arange(10.5, 30.5, 0.5) #создание массивов чисел с плавающей точкой 
c

array([10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. ,
       21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5,
       27. , 27.5, 28. , 28.5, 29. , 29.5, 30. ])

In [24]:
list(c) #переводим в список

[10.5,
 11.0,
 11.5,
 12.0,
 12.5,
 13.0,
 13.5,
 14.0,
 14.5,
 15.0,
 15.5,
 16.0,
 16.5,
 17.0,
 17.5,
 18.0,
 18.5,
 19.0,
 19.5,
 20.0,
 20.5,
 21.0,
 21.5,
 22.0,
 22.5,
 23.0,
 23.5,
 24.0,
 24.5,
 25.0,
 25.5,
 26.0,
 26.5,
 27.0,
 27.5,
 28.0,
 28.5,
 29.0,
 29.5,
 30.0]

In [54]:
numbers = [3,5,9,-1,3,1]
result = 0
for item in numbers:
    if item < 0:
        break #выходим из цикла, цикл останавливается
    result += item
print(result)

17


In [26]:
numbers = [3,5,9,-1,3,1]
result = 0
for item in numbers:
    if item < 0:
        continue #продолжаем цикл, пропуская не удовлетворяющее условию число
    result += item
print(result)

21


In [57]:
total = 0
for i in range(1,101,1):
    total += i
print(total)

5050


In [36]:
sum = 0
for x in range(10,31,2):
    sum += x**2+3
print(sum)

4873


In [60]:
lst = [4,10,5,-1.9] #поэлементное изменение списка
for i in range(len(lst)):
    lst[i] = lst[i]*2
print(lst)

[8, 20, 10, -3.8]


In [71]:
a = [] #создание списка с помощью range
for i in range(1,15):
    a.append(i)
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


In [41]:
a = list(range(1,15))
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


In [75]:
a = [i for i in range(1,15)] #списочное встраивание, списковое включение, генератор списка
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


In [45]:
lst = [4,10,5,-1.9]
lst2 = [i**2 for i in lst]
print(lst2)

[16, 100, 25, 3.61]


In [49]:
L = [c*3 for c in 'list' if c != 'i']
L

['lll', 'sss', 'ttt']

In [83]:
a = input('Введите первый список: ')
b = input('Введите второй список: ')
peresechenie = [i for i in a for j in b if i == j]
print(peresechenie)

Введите первый список:  мама
Введите второй список:  папа


['а', 'а', 'а', 'а']


In [85]:
a = [1,3,4]
b = [i+4 for i in a]
print(b)

[5, 7, 8]


In [86]:
b = [i+4 for i in [1,3,4]]
print(b)

[5, 7, 8]


In [91]:
def f(x):
    return x + 4

list(map(f,[2,5,7]))

[6, 9, 11]

In [94]:
counter = [1,3,4]
list(map((lambda x: x+4),counter)) #функция lambda используется, если нет потребности в создании отдельной функции

[5, 7, 8]

In [110]:
lst = [4,'5','6',8]
print(''.join(map(str,lst)))

4568


In [113]:
list(filter((lambda x: x < 0), range(-5,5)))

[-5, -4, -3, -2, -1]

In [114]:
list(filter((lambda x: x > 0), range(-5,5)))

[1, 2, 3, 4]

In [126]:
#вывести четные числа от 0 до 4, наиболее быстрый вариант
[x for x in range(5) if x%2==0]

[0, 2, 4]

In [125]:
#вывести четные числа от 0 до 4, средний по скорости вариант
list(filter((lambda x: x%2==0), range(5)))

[0, 2, 4]

In [127]:
#вывести четные числа от 0 до 4, самый медленный вариант
res = []
for i in range(5):
    if i%2==0:
        res.append(i)
res    

[0, 2, 4]

In [128]:
res = []
for x in [1,2,3]:
    for y in [100,200,300]:
        res.append(x+y)
res

[101, 201, 301, 102, 202, 302, 103, 203, 303]

In [129]:
[x+y for x in [1,2,3] for y in [100,200,300]]

[101, 201, 301, 102, 202, 302, 103, 203, 303]

In [135]:
#создание списка, состоящего из случайных элементов
#создание списка из 5 случайных чисел от 1 до 9 
from random import randint
A = [randint(1,9) for _ in range(5)] # нижним подчеркиванием обозначена переменная, не задействованная в дальнейших вычислениях
A

[1, 2, 6, 9, 3]

In [140]:
a = []
n = int(input()) #задаем кол-во элементов в массиве 
for i in range(n):
    new_element = int(input()) # задаем n элементов массива
    a.append(new_element) #добавляем их в массив
    #a.append(int(input()))
print(a) #выводим полученный массив

 3
 2
 1
 5


[2, 1, 5]


In [144]:
A = [int(input()) for i in range(int(input()))]
A

 3
 1
 5
 6


[1, 5, 6]

In [146]:
import math #на основе цикла for
b = []
for i in [2,4,9,16,25]:
    c = math.sqrt(i)
    b.append(c)
b

[1.4142135623730951, 2.0, 3.0, 4.0, 5.0]

In [147]:
import math #на основе функции map
def f(x):
    return math.sqrt(x)

list(map(f, [2,4,9,16,25]))

[1.4142135623730951, 2.0, 3.0, 4.0, 5.0]

In [150]:
import math #в виде генератора списка
A = [math.sqrt(i) for i in [2,4,9,16,25]]
A

[1.4142135623730951, 2.0, 3.0, 4.0, 5.0]

In [156]:
lst = [['A', 1], ['B', 2], ['C', 3]] #по факту - матрица
lst

[['A', 1], ['B', 2], ['C', 3]]

In [157]:
lst = [['A', 1], ['B', 2], ['C', 3]]
lst[0]

['A', 1]

In [158]:
lst = [['A', 1], ['B', 2], ['C', 3]]
lst[0][1]

1

In [160]:
#если хотим производить какие-то действия с набором чисел, то лучше работать не со списками, а с массивами, то есть 
#использовать NumPy
import numpy as np
ax = np.array([1,2,3,4])
ay = np.array([5,6,7,8])
ax*2

array([2, 4, 6, 8])

In [161]:
ax+10

array([11, 12, 13, 14])

In [164]:
ax+ay

array([ 6,  8, 10, 12])

In [165]:
ax*ay

array([ 5, 12, 21, 32])

In [174]:
import numpy as np #применение функции к массивам
def f(x):
    return np.sqrt(x)
ax = np.array([4,9,16,25])
f(ax)

array([2., 3., 4., 5.])

In [5]:
while True:
    a = str(input("Введите строку: "))
    if a == '1':
        print('Число 1')
    elif a == 'стоп':
        print('Выход из программы! До встречи!')
        break
    else:
        print('Что это')

Введите строку:  1


Число 1


Введите строку:  2


Что это


Введите строку:  стоп


Выход из программы! До встречи!


In [6]:
while True: #бесконечный цикл, будет выполняться всегда
    text = input("Введите число или стоп для выхода: ")
    if text == "стоп":
        print('Выход из программы! До встречи!')
        break
    elif text == '1':
        print("Число 1")
    else:
        print("Что это?!")

Введите число или стоп для выхода:  1


Число 1


Введите число или стоп для выхода:  2


Что это?!


Введите число или стоп для выхода:  стоп


Выход из программы! До встречи!


In [11]:
from random import randint 
b = randint(0,10)
i = 0
while i != 5:
    a = int(input("Введите число или выход для выхода: "))
    if a == 'выход':
        break
    elif a > b:
        print("Бери меньше")
        i += 1
    elif b > a:
        print("Бери больше")
        i += 1
    else:
        print("Правильно!")
        break

Введите число или выход для выхода:  3


Бери меньше


Введите число или выход для выхода:  2


Бери меньше


Введите число или выход для выхода:  1


Бери меньше


Введите число или выход для выхода:  0


Правильно!


In [13]:
s = 'aa3aBbb6ccc' #нахождение суммы чисел в строке 
total = 0
for i in range(len(s)):
    if s[i].isalpha():
        continue
    total += int(s[i])
print('сумма цифр:', total)

сумма цифр: 9


In [28]:
a = list(str(input("Введите число: ")))
total = 0
for i in range(len(a)):
    if int(a[i])%2 == 0:
        continue
    total += int(a[i])**2
print('Cумма квадратов нечетных цифр в числе: ', total)

Введите число:  343


Cумма квадратов нечетных цифр в числе:  18


In [4]:
total = 0
while True:
    a = str(input("Введите число или Стоп для выхода: "))
    if a == 'стоп':
        print("Сумма:", total)
        break
    elif a.isdigit():
        total += int(a)
    else:
        print("Ошибка ввода.")

Введите число или Стоп для выхода:  k


Ошибка ввода.


Введите число или Стоп для выхода:  f


Ошибка ввода.


Введите число или Стоп для выхода:  23
Введите число или Стоп для выхода:  56
Введите число или Стоп для выхода:  34
Введите число или Стоп для выхода:  стоп


Сумма: 113


In [24]:
s = '''В разные эпохи и у разных народов число Пи имело разное значение.
Например, в Древнем Египте оно равнялось 3.1604 у индусов оно приобрело
значение 3.162 китайцы пользовались числом, равным 3.1459
Буквенное обозначение число Пи получило только в 1706 году – оно происходит
от начальных букв двух греческих слов, означающих окружность и периметр.
Буквой π число наделил математик Джонс, а прочно вошла в математику она
уже в 1737 году.'''
a = s.split()
r = []
sum = 0 
for i in a:
    if i[0].isdigit():
        print(i)
        sum = sum + float(i)
        r.append(float(i))
print(sum)
len(r)

3.1604
3.162
3.1459
1706
1737
3452.4683


5

In [23]:
import numpy as np
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])